language: python

env:
  global:
    - secure: "Q9+k9JPi0OajzTDlz6bFbgCTBoE+VluWjFaSI5+AydB+QIvJkslGrm7Lm5zpdCz8JsmVdBaN9dmvrZLhoj9ZpXhetg7zRYVUfYDZZD68XZvDSgdS+2h99829K5WIlqTUeB/sRoyVpqVhZQXUXAjSl8SRVjhPpm4Y3j0qQ7ipDllVZXdhVoko+I2v1UNoJP9O515IXENwtdMXBebJT1AbvlfeuPz1hhPELbdk7qDyBhv2Ym2PI1WeMZ8aCXtxpq4z6n4sPir3wVTu4XSFfnrW0U7FSz/kjhrqHEij6D7BEqtPMwdCqyvOycZYzb6x/D8Un4hZO/BHO586NdiRsjR0xOuBTe5hHpGZEbTGKqPyYJVKik1Kz+W8flwhPCj54wp3JtdHo4bZ09v485j8WSA8XjfQ3jDqDH49TcD/Y/cg9/SuLeWYiticOiuGhoximapsx/dw/ltPElnuOqFeZeDxs8XpvosXujOEcICAbQLdjwRwy4OgQRNlWa96bvdhOmyBPvEv4Q4Uz4xC+mLvjfPHlKhonCYqkrpcxjkzEdVqpYDBkGLu1cmLZP34PHw+s2gIpwwNK9FIo7cj5E6pPeojP2hnZyKJjaNMVlHmWKHbwP+55S7R+fOUTRBTNCk+iFR4istjKbhIsarySlu1nnOCIiLnzAADW0Gm/LioIMXmQjo="

stages:
  - test
  - name: publish
    if: tag =~ ^\d+\.\d+\.\d+$

before_install:
  - pip install poetry tox-travis

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - poetry install

script: tox

jobs:
  include:
    - python: 3.8
      stage: test

    - stage: publish
      script: skip
      before_deploy:
        - poetry config pypi-token.pypi $PYPI_TOKEN
      python: 3.8
      deploy:
        provider: script
        script: poetry publish --build
        on:
          tags: true
